// Generated by https://quicktype.io

export interface Schedule {
  '2024': { [key: string]: DailyRoast[] };
}

export interface DailyRoast {
  id: number;
  roast: Roast;
  message: string;
  date: DateEnum;
}

export enum DateEnum {
  The20240 = '2024-0',
  The20240102120000 = '2024-01-02 12: 00: 00',
  The20240103091500 = '2024-01-03 09: 15: 00',
  The20240104183000 = '2024-01-04 18: 30: 00',
  The20240228163151 = '2024-02-28 16: 31: 51',
}

export enum Roast {
  Excited = 'excited',
  Happy = 'happy',
  Ok = 'ok',
  Tired = 'tired',
}
